services:
  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:17-0.102.0-ferretdb-2.1.0
    restart: on-failure
#    ports:
#      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2.3.1
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASS}@postgres:5432/postgres
      - MONGODB_ROOT_USERNAME=${POSTGRES_USER}
      - MONGODB_ROOT_PASSWORD=${POSTGRES_PASS}
    labels:
      org.springframework.boot.service-connection: mongo

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    ports:
      - "7700:7700"
    volumes:
      - "./data/meilisearch:/meili_data"

  seaweedfs:
    image: chrislusf/seaweedfs
    restart: on-failure
    ports:
      - "9333:9333"
      - "8888:8888"
      - "18888:18888"
    command: "server -master -filer -ip.bind=0.0.0.0"
    volumes:
      - ./data/seaweedfs:/data
