services:
  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:16
    restart: on-failure
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://username:password@postgres:5432/postgres
      - MONGODB_ROOT_USERNAME=username
      - MONGODB_ROOT_PASSWORD=password
    labels:
      org.springframework.boot.service-connection: mongo

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      MEILI_MASTER_KEY: random_master_key_12345
    ports:
      - "7700:7700"

  seaweedfs:
    image: chrislusf/seaweedfs
    restart: on-failure
    ports:
      - "9333:9333"  # master port
      - "8888:8888"  # filer port
      - "18888:18888"  # filer grpc port
    command: "server -master -filer -ip.bind=0.0.0.0"
    volumes:
      - ./seaweedfs-data:/data
