spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      skip:
        in-tests: true
  application:
    name: opdsko-spring

  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      port: 27017
      password: password
      username: postgres
#mongock:
#  migration-scan-package: com.github.asm0dey.opdsko_spring.migrations
#  runner-type: ApplicationRunner
#  track-ignored: false
#  test-enabled: false

#  datasource:
#    url: jdbc:postgresql://localhost:5432/opdsko
#    username: postgres
#    password: password

logging:
  level:
    root: debug
    com.zaxxer: info
    io.netty: info
    javax: info
    java:
      lang:
        ProcessBuilder: warn
    jdk: info
    okhttp3: info
    okio: info
    org.flywaydb: info
    org.hibernate: info
    org.jooq: debug
    org.pf4j: debug
    org.postgresql: info
    org.springframework: info
    reactor: info
    sun: info
    io: warn
    fb2: warn
    FB2: warn
    seaweedfs: warn
    org:
      apache:
        http: warn
      mongodb: warn
      springframework:
        boot:
          docker: warn
        data:
          mongodb:
            core:
              MongoTemplate: debug
              ReactiveMongoTemplate: debug
            repository:
              query: debug
scanner:
  sources:
#    - /home/finkel/Books/
    - /home/finkel/Downloads/flibusta_fb2_local.inpx

meilisearch:
  host: 127.0.0.1
  port: 7700
  api-key: random_master_key_12345

pf4j:
  plugin-dir: plugins

seaweedfs:
  filer-grpc-port: 18888
  filer-port: 8888
  host: localhost
  port: 9333