spring:
  application:
    name: opdsko-spring
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

logging:
  level:
    root: debug
    com.zaxxer: info
    io.netty: info
    javax: info
    jdk: info
    okhttp3: info
    okio: info
    org.flywaydb: info
    org.hibernate: info
    org.jooq: debug
    org.pf4j: debug
    org.postgresql: info
    org.springframework: info
    reactor: info
    sun: info

scanner:
  sources:
    - /home/finkel/Books/

meilisearch:
  host: http://127.0.0.1:7700
  api-key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1

pf4j:
  plugin-dir: plugins