spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      skip:
        in-tests: true
  application:
    name: opdsko-spring

  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      port: 27017
      password: password
      username: postgres

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-client-secret}
            scope:
              - email
              - profile
  main:
    banner-mode: off

logging:
  level:
    root: debug
    com.zaxxer: info
    io.netty: info
    javax: info
    java:
      lang:
        ProcessBuilder: warn
    jdk: info
    okhttp3: info
    okio: info
    org.flywaydb: info
    org.hibernate: info
    org.jooq: debug
    org.pf4j: debug
    org.postgresql: info
    org.springframework: info
    reactor: info
    sun: info
    io: warn
    fb2: warn
    FB2: warn
    seaweedfs: warn
    org:
      apache:
        http: warn
      mongodb: warn
      springframework:
        boot:
          docker: warn
        data:
          mongodb:
            core:
              MongoTemplate: debug
              ReactiveMongoTemplate: debug
            repository:
              query: debug
scanner:
  sources:
    #    - /home/finkel/Books/
    - /home/finkel/Downloads/flibusta_fb2_local.inpx

meilisearch:
  host: 127.0.0.1
  port: 7700
  api-key: random_master_key_12345

pf4j:
  plugin-dir: plugins

seaweedfs:
  filer-grpc-port: 18888
  filer-port: 8888
  host: localhost
  port: 9333

# Authentication configuration
# Environment variables:
# - AUTH_ENABLED: Set to "true" to enable authentication (default: false)
# - AUTH_ALLOWED_IPS: Comma-separated list of IP addresses or subnets that can bypass authentication
#   Example: AUTH_ALLOWED_IPS=127.0.0.1,192.168.1.0/24,::1
# - AUTH_ALLOWED_EMAILS: Comma-separated list of email addresses that are allowed to authenticate
#   Example: AUTH_ALLOWED_EMAILS=user1@example.com,user2@example.com
# - AUTH_APPLICATION_URL: The URL of the application, used for OAuth2 redirect
#   Example: AUTH_APPLICATION_URL=http://localhost:8080
auth:
  enabled: ${AUTH_ENABLED:false}
  allowed-ips:
  allowed-emails:
  application-url: ${AUTH_APPLICATION_URL:http://localhost:8080}

# Library configuration
# Environment variables:
# - LIBRARY_TITLE: The title of the library application displayed in the UI
#   Example: LIBRARY_TITLE=My Personal Library
library:
  title: ${LIBRARY_TITLE:Asm0dey's library}

mongock:
  test-enabled: false
  migration-scan-package: [ "com.github.asm0dey.opdsko_spring.migrations" ]
  index-creation: true
  enabled: true
