spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      skip:
        in-tests: false
  application:
    name: opdsko-spring

  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/opdsko
#    username: postgres
#    password: password

logging:
  level:
    root: info
    com.zaxxer: info
    io.netty: info
    javax: info
    jdk: info
    okhttp3: info
    okio: info
    org.flywaydb: info
    org.hibernate: info
    org.jooq: debug
    org.pf4j: debug
    org.postgresql: info
    org.springframework: info
    reactor: info
    sun: info

scanner:
  sources:
    - /home/finkel/Books/

meilisearch:
  host: 127.0.0.1
  port: 7700
  api-key: random_master_key_12345

pf4j:
  plugin-dir: plugins

